# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
  pull_request:
    branches:
      -[master]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Run test
        run: npm test
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_AUTH}}
        heroku_app_name: "workshop-pipeline" #Must be unique in Heroku
        heroku_email: "matansh@monday.com"

